artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/niranjankumarnk/mldemo/raw/main/breast-cancer.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion



data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/breast-cancer.csv
  STATUS_FILE: artifacts/data_validation/status.txt



data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/breast-cancer.csv




model_training:
  root_dir: artifacts/model_trainer
  data_path: artifacts/data_ingestion/breast-cancer.csv
  train_data_path: artifacts/data_transformation/train.csv
  test_data_path: artifacts/data_transformation/test.csv
  model_name: model.joblib
  target_column: schema.diagnosis
  



model_evaluation:
  root_dir: artifacts/model_evaluation
  data_path: artifacts/data_ingestion/breast-cancer.csv
  test_data_path: artifacts/data_transformation/test.csv
  model_path: artifacts/model_trainer/model.joblib
  metric_file_name: artifacts/model_evaluation/metrics.json